table 2025-07-24
	lineageTag: a6a8b610-66cd-4491-8782-c51af42d153d

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: cfbe0ed5-ee06-49ee-b2ba-30ccaa4f91de
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: b29d97a9-e9c6-47cb-b24f-9130601e27b8
			defaultHierarchy: LocalDateTable_9021ea6c-9ccd-493f-8a67-fd8bb2461184.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valor
		dataType: double
		lineageTag: b8be2fd3-6951-4ce5-b394-11764d4dd62f
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Identificador
		dataType: string
		lineageTag: 1e08249f-a7a4-4c9c-8e6c-8c37a46c416e
		summarizeBy: none
		sourceColumn: Identificador

		annotation SummarizationSetBy = Automatic

	column Descrição
		dataType: string
		lineageTag: 3f9cbeaa-5ba8-4901-95c1-3fbf5197f99d
		summarizeBy: none
		sourceColumn: Descrição

		annotation SummarizationSetBy = Automatic

	partition 2025-07-24 = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\dougl\OneDrive\Área de Trabalho\ESTUDOS\nubank-data-engineering-portfolio\data\bronze\2025-08-09\movimentacao.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Data", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

